## 딥러닝
- 정의 : 인간의 뇌가 작동하는 방식을 모방한 인공신경망을 사용해 학습하는 기술
- 신경망 : 핵심 요소는 인공신경망(neural network)
    - 신경망은 입력층, 은닉층, 출력층으로 구성
        - 각 층은 또 뉴런으로 구성 / 이 뉴런들은 가중치와 편항을 통해 서로 연결됨
- 학습과정 : 데이터를 받고 가중치를 조정하며 학습 -> 손실 함수를 최소화 하는 방향으로

## PyTorch
- Python기반 오픈소스 딥러닝 라이브러리
- 특징
    - 텐서 연산 : 뒤에 설명
    - 자동 미분 시스템 : 그레디언트(기울기) 계산 용이

## 기본 개념 설명
- 텐서(Tensor)
    - 정의 : 딥러닝에서 데이터를 표현하는 기본 단위, 벡터와 행렬, PT에서는 다차원배열

In [16]:
import torch
v = torch.tensor([1,2,3])
c = torch.tensor([[1],[2]]) # 주의 torch.tensor([1],[2])이건 실행이 안됨
m = torch.tensor([[1,2],[3,4]])
print(v)
print(c)
print(m)

tensor([1, 2, 3])
tensor([[1],
        [2]])
tensor([[1, 2],
        [3, 4]])


- 신경망 구조
    - 여러 레이어로 구성
    - 신경망의 비선형성을 도입하기 위해 사용되는 활성화 함수 (ReLU)

In [12]:
# 간단한 신경망 함수 모델 정의

import torch.nn as nn
import torch.nn.functional as F

class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc1 = nn.Linear(3,3) # 첫 번째 선형 레이어 : nn.Linear(입력, 출력) 

    def forward(self, x):
        x = F.relu(self.fc1(x)) # 활성화 함수 relu 적용
        return x


In [13]:
model = SimpleNet()

In [14]:
model

SimpleNet(
  (fc1): Linear(in_features=3, out_features=3, bias=True)
)

In [15]:
# 손실함수와 옵티마이저 설정

criterion = nn.MSELoss() # 평균제곱오차 손실함수
optimizer = torch.optim.SGD(model.parameters(), lr=0.001) # SGD 옵티마이저

## PyTorch 기본 사용법
- Tensor 생성 및 조작

In [1]:
import torch

x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

z = x + y
print(z)

tensor([5, 7, 9])


- 간단한 모델 구축 및 학습

In [2]:
import torch.nn as nn
import torch.optim as optim

class LinearRegressionModel(nn.Module): 
    def __init__(self):   # 모델 초기화 : 가중치 편향을 무작위로 시작
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(1, 1)  # 하나의 입력과 출력을 가짐

    def forward(self, x):
        return self.linear(x)

# 모델 및 손실 함수, 옵티마이저 초기화
model = LinearRegressionModel()
criterion = nn.MSELoss()  # 평균 제곱 오차 손실
optimizer = optim.SGD(model.parameters(), lr=0.01)  # 확률적 경사 하강법

# 간단한 데이터셋
inputs = torch.tensor([[1.], [2.], [3.]])   # 숫자뒤에 .을 왜붙힐까? : 머신러닝모델에서는 대부분 연산이 실수기반이라서
targets = torch.tensor([[2.], [4.], [6.]])
# 즉 둘 사이의 관계는 y=2x 가중치가 2인 선형함수

# 학습 루프
for epoch in range(100):  # 에포크 수
    optimizer.zero_grad()  # 그레이디언트 초기화
    outputs = model(inputs)  # 모델의 출력 계산
    loss = criterion(outputs, targets)  # 손실 계산
    loss.backward()  # 역전파
    optimizer.step()  # 가중치 갱신

    if (epoch+1) % 10 == 0:
        print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}')

Epoch [10/100], Loss: 1.8843
Epoch [20/100], Loss: 0.2486
Epoch [30/100], Loss: 0.0895
Epoch [40/100], Loss: 0.0713
Epoch [50/100], Loss: 0.0666
Epoch [60/100], Loss: 0.0634
Epoch [70/100], Loss: 0.0604
Epoch [80/100], Loss: 0.0575
Epoch [90/100], Loss: 0.0548
Epoch [100/100], Loss: 0.0523


In [10]:
inputs, targets, model

(tensor([[1.],
         [2.],
         [3.]]),
 tensor([[2.],
         [4.],
         [6.]]),
 LinearRegressionModel(
   (linear): Linear(in_features=1, out_features=1, bias=True)
 ))

In [11]:
outputs

tensor([[2.3380],
        [4.0725],
        [5.8070]], grad_fn=<AddmmBackward0>)

## 모델 예측 및 평가
- 예측


In [3]:
model.eval()  # 평가 모드로 전환
with torch.no_grad():  # 그레이디언트 계산 비활성화
    new_input = torch.tensor([[4.]])
    prediction = model(new_input)
    print(f"Prediction: {prediction.item()}")

Prediction: 7.542591571807861


- 모델 성능 평가

In [4]:
# 성능 평가를 위한 검증 데이터셋
val_inputs = torch.tensor([[4.], [5.], [6.]])
val_targets = torch.tensor([[8.], [10.], [12.]])

model.eval()  # 평가 모드로 전환
with torch.no_grad():  # 그레이디언트 계산 비활성화
    val_outputs = model(val_inputs)
    val_loss = criterion(val_outputs, val_targets)
    print(f"Validation Loss: {val_loss.item()}")

Validation Loss: 0.568464994430542
